# theme: minima # Example: if you want to use a theme, but we are using custom CSS for now.
# baseurl: "" # Set this if your site is in a subdirectory on the server, e.g., /my-repo
title: My School Website
description: Upcoming events and resources for our school.
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-menus
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-responsive-image
  - jekyll-scholar
  - jekyll-tidy
  - jekyll-watch
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-commonmark
  - jekyll-default-layout
  - jekyll-docs
  - jekyll-gist
  - jekyll-gitlab-pages
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-last-modified-at
  - jekyll-include-cache
  - jekyll-algolia
  - jekyll-archives
  - jekyll-assets
  - jekyll-babel
  - jekyll-brotli
  - jekyll-compose
  - jekyll-environment-variables
  - jekyll-gzip
  - jekyll-imagemagick
  - jekyll-inline-svg
  - jekyll-minifier
  - jekyll-polyglot
  - jekyll-purgecss
  - jekyll-pwa
  - jekyll-sanity
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-spotify
  - jekyll-tagging
  - jekyll-theme-architect
  - jekyll-theme-cayman
  - jekyll-theme-dinky
  - jekyll-theme-hacker
  - jekyll-theme-hyde
  - jekyll-theme-hydeout
  - jekyll-theme-jekyll
  - jekyll-theme-leap-day
  - jekyll-theme-merlot
  - jekyll-theme-midnight
  - jekyll-theme-minimal
  - jekyll-theme-modernist
  - jekyll-theme-primer
  - jekyll-theme-slate
  - jekyll-theme-tactile
  - jekyll-theme-time-machine
  - jemoji
  - kramdown-parser-gfm
  - liquid-c
  - rouge
  - safe_yaml
  - sassc
  - titlecase
  - webrick
